---
title: "Lab05"
author: "Huiqing Fu"
date: "2/21/2018"
output:
  github_document
  
---
```{r}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(readr)
```



#??????????????why imported data can't show properly?
```{r}
dat0 <- read_csv('../data/nba2017-players.csv')
head(dat0, 6)
tail(dat0)
```
```{r}
dat <- read.csv('../data/nba2017-players.csv')
head(dat)
tail(dat)
```

###Basic "dplyr" verbs
__Filtering, slicing, and selecting__
```{r}
# use slice() to subset the data by selecting the first 5 rows.
slice(dat,1:5)

# use slice() to subset the data by selecting rows 10, 15, 20, ..., 50.
slice(dat, seq(from = 10, to = 50, by = 5))

# use slice() to subset the data by selecting the last 5 rows.
slice(dat,(nrow(dat)-4):nrow(dat))

# use filter() to subset those players with height less than 70 inches tall.
filter(dat,height<70)

# use filter() to subset rows of Golden State Warriors ('GSW').
filter(dat, team == "GSW")

# use filter() to subset rows of GSW centers ('C').
filter(dat, team == "GSW", position == "C")

# use filter() and then select(), to subset rows of lakers ('LAL'), and then display their names.
LAL <- filter(dat, team == "LAL")
select(LAL,player)

# use filter() and then select(), to display the name and salary, of GSW point guards
GSW_PG <- filter(dat, team =="GSW", position == "PG")
select(GSW_PG, c(1,9))


# find how to select the name, age, and team, of players with more than 10 years of experience, making 10 million dollars or less.
Expe_mil <- filter(dat, experience > 10, salary <= 10000000)
select(Expe_mil, c(1,6,2))

# find how to select the name, team, height, and weight, of rookie players, 20 years old, displaying only the first five occurrences (i.e. rows)

rookie0 <- filter(dat, age == 20, experience <=1)
rookie1 <- select(rookie0, c(1,2,4,5))
slice(rookie1,1:5)

filter(dat, height>85)

```
### Adding new variables: mutate()
```{r}
# creating a small data frame step by step
gsw <- filter(dat, team == 'GSW')
gsw <- select(gsw, player, height, weight)
gsw <- slice(gsw, c(4, 8, 10, 14, 15))
gsw
```

### Reordering rows: arrange()

```{r}

# using the data frame gsw, add a new variable product with the product of height and weight. 
gsw1 <- mutate(gsw, product=height*weight)
gsw1



#  create a new data frame gsw3, by adding columns log_height and log_weight with the log transformations of height and weight.
log_height <- log(select(gsw,height))
log_weight <- log(select(gsw,weight))
#####?????????????????????????????????????????22222222222222222
gsw3 <- mutate(gsw,logHW=(log_height+log_weight))
gsw3




# use the original data frame to filter() and arrange() those players with height less than 71 inches tall, in increasing order.
height1 <- filter(dat, height<71)
arrange(height1)





#??????????????????what's the difference?????????????
# display the name, team, and salary, of the top-5 highest paid players
NTSofTop5 <- select(dat,c(1,2,9))
slice(NTSofTop5,1:5)

# display the name, team, and salary, for the top-5 highest paid players
NTSforTop5 <- select(dat,c(1,2,9))
slice(NTSforTop5,1:5)





# display the name, team, and points3, of the top 10 three-point players 
NTSofTop10 <- select(dat,c(1,2,13))
slice(NTSofTop10,1:10)


# create a data frame gsw_mpg of GSW players, that contains variables for player name, experience, and min_per_game (minutes per game), sorted by min_per_game (in descending order) 
gsw_mpg <- filter(dat,team == "GSW")
min_per_game = dat$minutes/dat$games
gsw_mpg1 <- select(gsw_mpg,c(1,7,10,11))
gsw_mpg2 <- mutate(gsw_mpg1,min_per_game = minutes/games)
gsw_mpg3 <- select(gsw_mpg2,c(1,2,5))
arrange(gsw_mpg3, desc(min_per_game))
```


###Summarizing values with summarise()


### Grouped operations
```{r}
# use summarise() to get the largest height value.
summarise(dat,max(height))

# use summarise() to get the standard deviation of points3.
 summarise(dat,sd(points3))
 
# use summarise() and group_by() to display the median of three-points, by team.
 summarise(
   group_by(dat,team),
   median_points3 = median(points3)
 )
 
# display the average triple points by team, in ascending order, of the bottom-5 teams (worst 3pointer teams)

triplePoints <- arrange(
         summarise(
         group_by(dat, team),
         avg_points = mean(points3)),
         avg_points
)
slice(triplePoints,(nrow(triplePoints)-4):nrow(triplePoints))

# obtain the mean and standard deviation of age, for Power Forwards, with 5 and 10 years (including) years of experience.
PF <- filter(dat, position=="PF", experience==5 | experience == 10)
PF
summarise(PF,
        avgAge=mean(age),
        sdAge=sd(age)  
          )




```



#First contact with ggplot()
```{r scatterplot1}
#scatterplot option1
# Use the data frame gsw to make a scatterplot of height and weight.
ggplot(data = gsw)+
  geom_point(aes(x=height,y=weight))
```
```{r}
# Find out how to make another scatterplot of height and weight, using geom_text() to display the names of the players.
ggplot(data = gsw, aes(x=height,y=weight))+
  geom_point()+
  geom_text(aes(label=player))
```
```{r}
# Get a scatter plot of height and weight, for ALL the warriors, displaying their names with geom_label().
ggplot(data = gsw, aes(x=height,y=weight))+
  geom_point()+
  geom_label(aes(label = player))
```


```{r}
# Get a density plot of salary (for all NBA players).
ggplot(data=dat, aes(x=salary)) +
  geom_density(fill = "#CCEE01", color = "#22BB21", linetype = "dashed")
  
```



```{r}
# Get a histogram of points2 with binwidth of 50 (for all NBA players).
ggplot(data=dat, aes(x = points2)) +
  geom_histogram(bins = 50, color = "pink", fill = "#CC2303")
```

# Get a barchart of the position frequencies (for all NBA players).
```{r}
ggplot(data = dat, aes(x=position)) +
  geom_bar(color="yellow", fill = '#22BB21')
```


```{r}
# Make a scatterplot of experience and salary of all Centers, and use geom_smooth() to add a regression line.
ggplot(data = dat[dat$position == "C",], aes(x= experience, y = salary)) +
  geom_point(colour = "red") +
  geom_smooth(method='lm', fill = "yellow")
 
```



```{r}
# Repeat the same scatterplot of experience and salary of all Centers, but now use geom_smooth() to add a loess line (i.e. smooth line).
ggplot(data = dat[dat$position == "C",], aes(x= experience, y = salary)) +
  geom_point(colour = "orange") +
  geom_smooth(method = "loess")

```




